name: Run checks
on:
  pull_request:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: checkout repo
      uses: actions/checkout@v5
    - name: install nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: setup nix cache
      uses: DeterminateSystems/magic-nix-cache-action@v13
    - name: run build checks
      run: nix flake check
